### ISSUE TITLE
Unclear what this package does

### ISSUE THREAD

**Issue by Nantris** [henriquecarv/gulp-bump-beta#20]
@henriquecarv thanks for making this! I've felt that gulp-bump could handle beta versioning a bit better for a while.

I'm not clear on what this package does though. Would it be possible to add example output to the project readme?

**Comment by henriquecarv** [comment]
@Slapbox no problem.
About gulp bump being able to handle bumping to beta:

To be completely honest, today if I had to bump 'beta' labeled version, I would go back and look at [it](https://github.com/stevelacy/gulp-bump)  again and find a better way to do it.

When I created this solution, I went through some docs and only found some hacky ways of achieving my goal.

Per your request, will definetly add an output example to README.

**Comment by henriquecarv** [comment]
@Slapbox 
There you go.
You might want to check it out the updated README file.

**Comment by Nantris** [comment]
There's always a better way you can't see until you're done. Thanks for adding that to the README!
